"""
Application Database Utilities
==============================

This package contains helper functions responsible for storing computed
technical indicators generated by the feature engineering pipeline.

Unlike the API database package, which defines the database
configuration and schema, this package provides higher-level utility
functions used by worker processes.

Primary Responsibilities
------------------------
• Save engineered features.
• Retrieve previously computed observations.
• Simplify database interaction for worker modules.
"""